services:
  app:
    build: .
    container_name: claudecode_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+asyncpg://claudecode:claudecode123@postgres:5432/claudecode}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: poetry run uvicorn claudecode.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:15
    container_name: claudecode_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-claudecode}
      POSTGRES_USER: ${POSTGRES_USER:-claudecode}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-claudecode123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U claudecode -d claudecode"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: